version: '3.8'

# Configuración optimizada para producción
# Usar con: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  db:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
  web:
    restart: always
    environment:
      # Deshabilitar modo debug en producción
      FLASK_DEBUG: "false"
      FLASK_ENV: "production"
      # Aumentar workers para producción
      WEB_CONCURRENCY: ${WEB_CONCURRENCY:-8}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    # Límites de recursos
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Nginx como proxy reverso (opcional pero recomendado)
  nginx:
    image: nginx:alpine
    container_name: sesame_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./static:/usr/share/nginx/html/static:ro
    depends_on:
      - web
    networks:
      - sesame_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"